services:
  traefik:
    image: traefik:v3.6
    command:
      - "--providers.file.filename=/etc/traefik/dynamic.yml" # Use a file, not the socket
      - "--entrypoints.web.address=:9417"
    ports:
      - "9417:9417"
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: ghcr.io/iauu/news-aggregator-server:latest
    environment:
      - RUST_LOG=info
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./model_data:/app/model_data
    depends_on:
      - database
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ghcr.io/iauu/news-aggregator-client:latest
    restart: unless-stopped
  database:
    image: pgvector/pgvector:pg18-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql
    restart: unless-stopped
